Repository EdeiltonSO/embarcatech-g8-sub7-dep-ver, pull requests merged in 2024-12, with the labels that each got.

#13 docs: Adicionado a descrição da funcionalidade de conversor de comprimento
  README.md
Labels: documentação

#15 docs: foi adicionado ao readme uma breve explicação sobre o conversor…
  README.md
Labels: documentação

#16 feature: Adicionado o conversor de massa ao menu principal
  Makefile
  README.md
  conv-massa/conv-massa.c
  conv-massa/conv-massa.h
  index.c
Labels: novidade

#17 Implementa Conversor de Volume
  con-volume/conv-Volume.c
Labels: novidade

#18 feat: add conversor de volume ao menu principal
  Makefile
  README.md
  conv-volume/conv-volume.c
  conv-volume/conv-volume.h
  index.c
Labels: novidade

#19 feat: add documentação dos conversores de dados e volume
  README.md
Labels: documentação

#20 Bugfix/fflush
  Makefile
  README.md
  conv-comp/conv-comp.c
  conv-dados/conv-dados.c
  conv-dados/conv-dados.h
  conv-massa/conv-massa.c
  conv-vel/conv-vel.c
  index.c
Labels: bugfix
